# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

# Departing from the implicit _user.c scheme
XDP_TARGETS  := xdp_kern_drop xdp_kern_scramble xdp_kern_reflect
USER_TARGETS := xdp_user_drop xdp_user_scramble xdp_user_reflect

LIBBPF_DIR = libbpf/src/
COMMON_DIR = common/

include $(COMMON_DIR)/common.mk
LIBS += -lpthread -lrt
